packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/cells/resource-cell.vue
packages/oc-pages/dashboard/components/cells/shared/deployment-status-icon.vue
packages/oc-pages/dashboard/dashboard.vue
packages/oc-pages/dashboard/pages/environment.vue
packages/oc-pages/dashboard/store/modules/deployment-info.js
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/pipelines.js
packages/oc-pages/vue_shared/components/oc/Status.vue

This requires https://github.com/onecommons/gitlab-oc/pull/425 to function

Use 'unencrypted_var' for variables that aren't sensitive

---

packages/oc-pages/project_overview/components/header.vue

https://github.com/onecommons/gitlab-oc/issues/562

Prefer livePreview from dataset

---

packages/oc-pages/project_overview/components/shared/oc_inputs/GithubMirroredRepoImageSource.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/LocalImageRepoSource.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployments.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/vue_shared/client_utils/pipelines.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/client_utils/user.js

Fix username/password, link to imported projects, trigger upstream

---

packages/oc-pages/vue_shared/oc_ci_variable_list/components/ci_variable_modal.vue
packages/oc-pages/vue_shared/oc_ci_variable_list/components/ci_variable_table.vue

https://github.com/onecommons/gitlab-oc/issues/918

Restore file and masked options for environment variables

---

packages/oc-pages/project_overview/components/shared/oc_inputs.vue

https://github.com/onecommons/gitlab-oc/issues/917

Wrap inputs and additional tab inputs inside of el-card

---

packages/oc-pages/dashboard/dashboard.vue

https://github.com/onecommons/gitlab-oc/issues/926

Fix dashboard flash width and layout responsiveness w/ collapsed sidebar

---

packages/oc-pages/project_overview/components/shared/oc_inputs.vue

https://github.com/onecommons/gitlab-oc/issues/1060

Fix interaction between default: _generate and deleting/missing envvars

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/dashboard/store/modules/deployment-info/deployment-item.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/pipelines.js

https://github.com/onecommons/gitlab-oc/issues/777

Start on manual incremental deploy btn 

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue

https://github.com/onecommons/gitlab-oc/issues/1061

Always display 'View Deployment History' 

---

packages/oc-pages/project_overview/components/environment-creation-dialog.vue
packages/oc-pages/vue_shared/client_utils/dashboard.js

https://github.com/onecommons/gitlab-oc/issues/1070

Handle kubernetes/digital ocean env creation on overview 

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue

https://github.com/onecommons/gitlab-oc/issues/1073

Link to manifest directory in project repository 

---

packages/oc-pages/project_overview/components/main.vue
packages/oc-pages/project_overview/components/shared/oc_template_header.vue
packages/oc-pages/project_overview/components/template/template_buttons.vue
packages/oc-pages/project_overview/pages/projects/index.vue
packages/oc-pages/project_overview/store/modules/deployments.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/vue_shared/client_utils/environments.js
packages/oc-pages/vue_shared/components/oc/environment-selection.vue

https://github.com/onecommons/gitlab-oc/issues/867
Currently 2/6 tasks

Allow deploying into another dashboard

---

packages/oc-pages/project_overview/components/shared/oc_inputs/LocalImageRepoSource.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCloudMirroredRepoImageSource.vue
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/vue_shared/client_utils/group.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/client_utils/user.js

https://github.com/onecommons/gitlab-oc/issues/1108

 Track group access tokens for group dashboard projects

---

packages/oc-pages/dashboard/store/modules/table_data.js
packages/oc-pages/project_overview/store/modules/project.js

https://github.com/onecommons/gitlab-oc/issues/943 / https://github.com/onecommons/gitlab-oc/issues/1118
also attempted to fix https://github.com/onecommons/gitlab-oc/issues/1096

Loosen criteria for display resources on deployment tables

---

packages/oc-pages/project_overview/components/shared/oc_card.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCloudMirroredRepoImageSource.vue
packages/oc-pages/project_overview/components/shared/oc_list.vue
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/projects.js

One way of solving https://github.com/onecommons/gitlab-oc/issues/1076

Get mirrored image source working with pre-filled inputs

---

packages/oc-pages/project_overview/components/shared/oc_list.vue
packages/oc-pages/project_overview/store/modules/template_resources.js

https://github.com/onecommons/gitlab-oc/issues/1132

Always display shared resource attributes vs properties 

---

packages/oc-pages/vue_shared/components/console-wrapper.css
packages/oc-pages/vue_shared/components/console-wrapper.vue

https://github.com/onecommons/gitlab-oc/issues/1114

Load console component style overrides dynamically

---

packages/oc-pages/dashboard/router/index.js

https://github.com/onecommons/gitlab-oc/issues/1101

Intercept sidenav links on dashboard page with Vue router

---

packages/oc-pages/project_overview/components/shared/oc_list.vue

https://github.com/onecommons/gitlab-oc/issues/1139

List both properties and attributes when available 

---

packages/oc-pages/project_overview/store/modules/project.js

https://github.com/onecommons/unfurl-gui/pull/184

Fix regression from PR 184

---

packages/oc-pages/dashboard/components/share-resource-toggle.vue
packages/oc-pages/vue_shared/client_utils/gitlab-issues.js
packages/oc-pages/vue_shared/client_utils/unfurl-invocations.js
packages/oc-pages/vue_shared/components/oc/local-deploy.vue

Requires https://github.com/onecommons/gitlab-oc/pull/1134, but does not break anything without it
[See usage details here](https://github.com/onecommons/gitlab-oc/issues/974#issuecomment-1267612544)

Enable public resource sharing request & Require connect for a resource to be shareable

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue

https://github.com/onecommons/gitlab-oc/issues/1115

Temporary hide delete

---

packages/oc-pages/project_overview/components/shared/oc_list.vue
packages/oc-pages/project_overview/store/modules/project.js

https://github.com/onecommons/gitlab-oc/issues/1152

Don't show second incremental deploy toggle in attributes

---

packages/oc-pages/project_overview/components/shared/oc_list.vue

https://github.com/onecommons/gitlab-oc/issues/1157

Fix empty inputs for imported Resources in deployment view 

---

packages/oc-pages/project_overview/components/shared/oc_inputs/GithubMirroredRepoImageSource.vue

https://github.com/onecommons/gitlab-oc/issues/1156

Fix error setting upstream info for GithubMirroredRepoImageSource

---

packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/components/oc/deployment-resources.vue

https://github.com/onecommons/gitlab-oc/issues/1164

Hide hidden types in external resource creation 

---

packages/oc-pages/dashboard/components/share-resource-toggle.vue

https://github.com/onecommons/gitlab-oc/issues/1167

Don't limit sharable resources to one with "connect" operations https

---

packages/oc-pages/project_overview/components/open-cloud-deployments.vue

now `cloud | testbed project | deployment`

Reorder open cloud deployments table

---

packages/oc-pages/dashboard/pages/home.vue

https://github.com/onecommons/gitlab-oc/issues/1177

Add README to dashboard home

---

packages/oc-pages/dashboard/components/dashboard-welcome.vue

https://github.com/onecommons/gitlab-oc/issues/1191

Change shared dashboard welcome message to reference current dashboard

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue

https://github.com/onecommons/gitlab-oc/issues/1190

Always allow editing deployments, show warning on non-drafts 

---

packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/GithubMirroredRepoImageSource.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCloudMirroredRepoImageSource.vue
packages/oc-pages/project_overview/components/shared/oc_list.vue
packages/oc-pages/project_overview/store/modules/deployments.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/components/oc/deployment-scheduler.vue

https://github.com/onecommons/gitlab-oc/issues/875

Fix connect for connectable image source types

---

packages/oc-pages/project_overview/store/modules/environments.js

https://github.com/onecommons/gitlab-oc/issues/1197

Never create user access token for a dashboard we don't own 

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue

https://github.com/onecommons/gitlab-oc/issues/1196

Allow teardown on failed deployments

---

packages/oc-pages/dashboard/components/dashboard-welcome.vue
packages/oc-pages/dashboard/components/quantity-card.vue

https://github.com/onecommons/gitlab-oc/issues/1202

Don't show quantity card creation buttons or welcome on dashboards we don't maintain

---

packages/oc-pages/dashboard/pages/environments-index.vue

https://github.com/onecommons/gitlab-oc/issues/1202

Don't show create environment button if user doesn't have edit permission

---

packages/oc-pages/project_overview/store/modules/deployment_template_updates.js

This implementation doesn't apply exclusively to resource templates

Don't commit resource templates with directive: 'predefined'

---

packages/oc-pages/project_overview/components/template/template_buttons.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js

https://github.com/onecommons/gitlab-oc/issues/1204

Don't allow navigating away while deployment is being started

---

packages/oc-pages/vue_shared/components/console-wrapper.vue

https://github.com/onecommons/gitlab-oc/issues/1231

Fix clone button not working after sync

---

packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployments.js
packages/oc-pages/project_overview/store/modules/environments.js

https://github.com/onecommons/gitlab-oc/issues/1234

Fix save draft regression; Add additional commit messages (6/7)

---

packages/oc-pages/project_overview/store/modules/environments.js

Vue is not happy about this on prod.

Fix missing variable assignment

---

packages/oc-pages/project_overview/store/modules/environments.js

https://github.com/onecommons/gitlab-oc/issues/1249

Slugify cloned environment names 

---

packages/oc-pages/dashboard/components/share-resource-toggle.vue
packages/oc-pages/dashboard/store/modules/deployment-info/deployment-item.js
packages/oc-pages/project_overview/store/modules/deployments.js
packages/oc-pages/vue_shared/client_utils/environments.js
packages/oc-pages/vue_shared/client_utils/envvars.js
packages/oc-pages/vue_shared/lib/deployment-template.js

https://github.com/onecommons/gitlab-oc/issues/1248

Don't try to copy '*' variables when cloning into another environment

---

packages/oc-pages/project_overview/components/shared/oc_inputs/LocalImageRepoSource.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCloudMirroredRepoImageSource.vue
packages/oc-pages/vue_shared/client_utils/projects.js

https://github.com/onecommons/gitlab-oc/issues/1247

Don't use UNFURL_ACCESS_TOKEN to fetch project list 

---

packages/oc-pages/project_overview/store/modules/template_resources.js

https://github.com/onecommons/gitlab-oc/issues/1251

Don't commit invalid properties/dependencies with imported resources

---

packages/oc-pages/project_overview/components/template/template_buttons.vue
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/components/oc/ErrorSmall.vue

https://github.com/onecommons/gitlab-oc/issues/1266

Add feedback to disabled deploy button

---

packages/oc-pages/project_overview/store/modules/template_resources.js

https://github.com/onecommons/gitlab-oc/issues/1261

Ensure cards are removed after disconnect

---

packages/oc-pages/project_overview/store/modules/template_resources.js

https://github.com/onecommons/gitlab-oc/issues/1261

Ensure cards are removed after disconnect (handover)

---

packages/oc-pages/project_overview/store/modules/project.js

https://github.com/onecommons/gitlab-oc/issues/1280

Fix overview page edit deployed button

---

packages/oc-pages/project_overview/store/modules/template_resources.js

https://github.com/onecommons/gitlab-oc/issues/1275

Disregard ensemble.json ResourceType dictionary when editing deployments

---

packages/oc-pages/dashboard/dashboard.vue
packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/dashboard/pages/environment.vue
packages/oc-pages/dashboard/store/modules/deployment-info.js
packages/oc-pages/dashboard/store/modules/table_data.js
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCloudMirroredRepoImageSource.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/project_overview/store/modules/misc.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/pipelines.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/components/oc/oc-properties-list.vue
packages/oc-pages/vue_shared/graphql.js
scripts/src/membership-test.js

Also additions/fixes with:
* trigger service account deployment for GCP
* fix deployment blueprint source with clones
* add fields to primary provider properties list,
* post environment variables before commiting changes to dashboard
repository

Implement atomic deployment changes

---

packages/oc-pages/dashboard/pages/environment.vue
packages/oc-pages/dashboard/router/index.js
packages/oc-pages/project_overview/pages/projects/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/project_overview/store/modules/misc.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/components/oc/deployment-resources.vue
packages/oc-pages/vue_shared/components/oc/oc-properties-list.vue
packages/oc-pages/vue_shared/components/oc/redacted.vue

https://github.com/onecommons/gitlab-oc/issues/1289

Frontend changes for additional providers

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/dashboard.vue
packages/oc-pages/dashboard/index.js
packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/project_overview/components/main.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/GithubMirroredRepoImageSource.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/project_overview/store/modules/misc.js
packages/oc-pages/project_overview/store/modules/project.js
packages/oc-pages/vue_shared/client_utils/gitlab-issues.js
packages/oc-pages/vue_shared/client_utils/oc-flash.js

I was looking for the instance envvars doc to add one for our service desk.  I have the hardcoded value in just one place, so it will be easy to switch to an instance var.
https://github.com/onecommons/gitlab-oc/issues/1310

Update issues to work with gitlab service desk (updated to 'onecommons/support')

---

packages/oc-pages/project_overview/pages/projects/index.vue
packages/oc-pages/project_overview/store/modules/project.js
packages/oc-pages/vue_shared/client_utils/comments.js
packages/oc-pages/vue_shared/compat.js
packages/oc-pages/vue_shared/components/notes-wrapper.vue
packages/oc-pages/vue_shared/components/oc/oc-tab.vue

Styling issues fixed:
* hide system notes, but not replies
* hide close issue button for devs/maintainers
* hide non-functional fullscreen button
* hide markdown + quick actions toolbar text

Comments section: fix styling issues and display comments count

---

packages/oc-pages/project_overview/components/header.vue

https://github.com/onecommons/gitlab-oc/issues/1327

Use tree path provided by dataset for 'View Project' link

---

packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/dashboard/store/modules/deployment-info/deployment-item.js

https://github.com/onecommons/gitlab-oc/issues/1344

Fix local deploys being considered non-drafts prior to pushing

---

packages/oc-pages/dashboard/components/cells/resource-cell.vue

https://github.com/onecommons/gitlab-oc/issues/1346

Fix invalid resource links in "Your Deployments" tab

---

packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/open-live-app.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/dashboard/store/index.js
packages/oc-pages/project_overview/components/shared/oc_card.vue
packages/oc-pages/project_overview/store/index.js
packages/oc-pages/vue_shared/components/oc/deployment-resources.vue
packages/oc-pages/vue_shared/store_modules/health-check.js

https://github.com/onecommons/gitlab-oc/issues/1371
depends on type changes from https://gitlab.com/onecommons/unfurl-types/-/tree/detjensrobert/health-checks

Perform health-check to indicate whether a deployment/live app is ready (PR into unfurl-server-url)

---

packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/open-live-app.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/dashboard/store/index.js
packages/oc-pages/project_overview/components/shared/oc_card.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/UnfurlCNamedDNSZone.vue
packages/oc-pages/project_overview/components/shared/oc_inputs/index.js
packages/oc-pages/project_overview/components/shared/oc_inputs/mixins.js
packages/oc-pages/project_overview/store/index.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/crossorigin-xhr.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js
packages/oc-pages/vue_shared/components/oc/deployment-resources.vue
packages/oc-pages/vue_shared/oc-components.js
packages/oc-pages/vue_shared/store_modules/health-check.js

Included health check for refactor (wasn't marged into handover for some reason)

Start on DNS CNAME component (UnfurlUserDNSZone)

---

packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/project_overview/store/modules/deployments.js

https://github.com/onecommons/gitlab-oc/issues/1396

Fix navigation prompt race condition with clone deployment

---

packages/oc-pages/dashboard/router/index.js

https://github.com/onecommons/gitlab-oc/issues/1312

Force highlight topnav dashboard button when we're in a dashboard view

---

packages/oc-pages/dashboard/store/modules/table_data.js

https://github.com/onecommons/unfurl-gui/issues/322

Remove deep clone and redundant store population in dashboard table loader

---

packages/oc-pages/dashboard/components/share-resource-toggle.vue

This is not a very efficient implementation, but this was much less risky to add a simple lock

Do not use stale data in patches when user shares multiple resources

---

packages/oc-pages/project_overview/components/header.vue
packages/oc-pages/project_overview/components/header/overview-share-modal.vue
packages/oc-pages/vue_shared/compat.js

Depends on https://github.com/onecommons/gitlab-oc/pull/1445

Add share modal embeddable deploy button

---

packages/oc-pages/project_overview/components/main.vue
packages/oc-pages/project_overview/components/shared/oc_inputs.vue
packages/oc-pages/project_overview/components/shared/oc_list.vue
packages/oc-pages/project_overview/components/template/deploy_button.vue
packages/oc-pages/project_overview/components/template/template_buttons.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js

Merge requests (WIP/POC)

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/cells/deployment-controls/control-buttons.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/deployments.js

https://github.com/onecommons/gitlab-oc/issues/1355

Support renaming deployments

---

packages/oc-pages/vue_shared/components/console-wrapper.vue

https://github.com/onecommons/gitlab-oc/issues/1466

Fix broken console scrolling with permalink

---

packages/oc-pages/project_overview/components/shared/oc_inputs.vue

https://github.com/onecommons/gitlab-oc/issues/1470

Fix formily field/label alignment

---

packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/project_overview/store/modules/project.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js

Everything works as before without gitlab-oc changes `project_visibility: @project.visibility`

Don't send x-git-credentials when blueprint project is public (14.9)

---

packages/oc-pages/dashboard/pages/deployment.vue
packages/oc-pages/project_overview/store/modules/project.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js

Everything works as before without gitlab-oc changes `project_visibility: @project.visibility`

Don't send x-git-credentials when blueprint project is public

---

packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/vue_shared/client_utils/environments.js

https://github.com/onecommons/gitlab-oc/issues/1509

Use unfurl error response in error component context when available (14.9)

---

packages/oc-pages/project_overview/store/modules/template_resources.js

Reverts changes from https://github.com/onecommons/gitlab-oc/issues/1275

Use resource types from exported deployments

---

packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/vue_shared/client_utils/environments.js

https://github.com/onecommons/gitlab-oc/issues/1509

Use unfurl error response in error component context when available

---

packages/oc-pages/vue_shared/client_utils/envvars.js

https://github.com/onecommons/gitlab-oc/issues/1519

Prevent trying to patch existing envvars cached without an ID

---

packages/oc-pages/vue_shared/client_utils/envvars.js

Regression caused by fix for https://github.com/onecommons/gitlab-oc/issues/1519

Fix regression in envvars patch change (oc-1519)

---

packages/oc-pages/vue_shared/components/oc/deployment-resources.vue

This reverts commit ecbdda72504ab04d77ac851f1682c2e6019346c0.

Revert "Add external resource: force tab ordering, set min height"

---

packages/oc-pages/vue_shared/components/oc/deployment-resources.vue

Fix regression in add external resource tab ordering fix

---

packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployments.js

Also changed error message for no types found

Lookup _sourceinfo on clone

---

packages/oc-pages/dashboard/dashboard.vue
packages/oc-pages/vue_shared/components/oc/local-deploy.vue

Support #clone-instructions fragment on dashboard views to open clone instructions modal

---

packages/oc-pages/project_overview/store/modules/deployment_template_updates.js

Aims to resolve https://github.com/onecommons/gitlab-oc/issues/1579

Attempt to fix private registries not working for container apps

---

packages/oc-pages/project_overview/components/shared/oc_inputs.vue

See [#1578](https://github.com/onecommons/gitlab-oc/issues/1578)

Minor formily layout fixes

---

packages/oc-pages/project_overview/components/shared/oc_inputs.vue

Formily: handle empty additional properties

---

packages/oc-pages/vue_shared/client_utils/unfurl-server.js
packages/oc-pages/vue_shared/lib/normalize.js

Plus - no implementation_requirements=undefined

Don't allow alias types to be selected

---

packages/oc-pages/project_overview/components/main.vue
packages/oc-pages/project_overview/pages/projects/index.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js

- Correctly add ResourceTemplate entry to deployment template when not present
- Correctly determine edit permissions
- Don't fetch user environment when editing blueprints

Handle additional edge cases for editing blueprints

---

packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/environments.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/unfurl-server.js

Also do not automatically send main for blueprints

Use package version from deployment when editing existing

---

packages/oc-pages/vue_shared/components/oc/detect-icon.vue
packages/oc-pages/vue_shared/components/oc/markdown-view.vue

https://github.com/onecommons/gitlab-oc/issues/1592

Changes for cloud chart

---

packages/oc-pages/dashboard/components/cells/deployment-controls.vue
packages/oc-pages/dashboard/components/dashboard-router-link.vue
packages/oc-pages/dashboard/components/tables/deployment-index-table/last-deploy.vue
packages/oc-pages/dashboard/store/modules/deployment-info/deployment-item.js
packages/oc-pages/dashboard/store/modules/table_data.js
packages/oc-pages/package.json
packages/oc-pages/project_overview/pages/projects/index.vue
packages/oc-pages/project_overview/pages/templates/index.vue
packages/oc-pages/project_overview/store/modules/deployment_template_updates.js
packages/oc-pages/project_overview/store/modules/project.js
packages/oc-pages/project_overview/store/modules/project_application_blueprint.js
packages/oc-pages/project_overview/store/modules/template_resources.js
packages/oc-pages/vue_shared/client_utils/projects.js
packages/oc-pages/vue_shared/components/oc/environment-selection.vue

Additional improvements:
- Suppress redundant console error messages
- Fix bugs in merge request/developer user flow

Support deploying on the blueprint main branch
